CompPrehension/CompPrehension

pom.xml, src/main/java/com/example/demo/models/businesslogic/Domain.java, src/main/java/com/example/demo/models/businesslogic/backend/PelletBackend.java, src/main/java/com/example/demo/models/businesslogic/backend/SWRLBackend.java, src/main/java/com/example/demo/models/entities/QuestionLaw.java, src/test/java/com/example/demo/models/businesslogic/StrategyTest.java
Make tests working again.
Add domain question creation for strategy test.
=> Revive tests

src/main/java/com/example/demo/models/businesslogic/backend/PelletBackend.java, src/main/java/com/example/demo/models/businesslogic/backend/SWRLBackend.java
Add format to define owl initialization (classes, object and data properties), fill ontology with data (create individuals and set object and data properties), fill SWRL rules from laws.
=> Add some specific to backend call

pom.xml, src/main/java/com/example/demo/controllers/QuestionController.java, src/main/java/com/example/demo/models/businesslogic/ProgrammingLanguageExpressionDomain.java, src/main/java/com/example/demo/models/businesslogic/QuestionRequest.java, src/main/java/com/example/demo/models/businesslogic/Strategy.java, src/main/java/com/example/demo/models/businesslogic/backend/Backend.java, src/main/java/com/example/demo/models/businesslogic/backend/PelletBackend.java, src/main/java/com/example/demo/models/businesslogic/backend/SWRLBackend.java, src/main/java/com/example/demo/models/entities/LawFormulation.java, src/test/java/com/example/demo/models/businesslogic/ProgrammingLanguageExpressionDomainTest.java
Temporarily added all object and data properties and all SWRL rules.
Make simple test using these components that receive result.
Still waiting for domainService to get SWRL rules from law, not straight from domain.
next steps:
- split init backend facts (object and data properties) and link with concepts
- split all SWRL rules to corresponding laws
=> Add test with backend call

pom.xml, src/main/java/com/example/demo/models/businesslogic/ProgrammingLanguageExpressionDomain.java, src/test/java/com/example/demo/models/businesslogic/backend/PelletBackendTest.java, src/test/resources/before-test-data.json, src/test/resources/has-operand-test-data.json, src/test/resources/simple-ontology-test-data.json
Comment SWRL rules on complex_beginning/complex_ending due some strange errors.
=> Add a lot of tests for Pellet backend.

src/main/java/com/example/demo/models/businesslogic/ProgrammingLanguageExpressionDomain.java, src/main/java/com/example/demo/models/businesslogic/backend/PelletBackend.java, src/main/java/com/example/demo/models/businesslogic/backend/SWRLBackend.java, src/main/java/com/example/demo/models/entities/Mistake.java, src/test/java/com/example/demo/models/businesslogic/SystemIntegrationTest.java
Сделал объяснение ошибок, добавил в тест.
Добавил в Mistake бекенд-факты для объяснения ошибок.
=> Double save fail

src/main/java/com/example/demo/Service/QuestionService.java, src/main/java/com/example/demo/controllers/LtiController.java, src/main/java/com/example/demo/dto/InteractionDto.java, src/main/java/com/example/demo/dto/QuestionAnswerDto.java, src/main/java/com/example/demo/dto/SessionInfoDto.java, src/main/java/com/example/demo/dto/UserInfoDto.java, src/main/java/com/example/demo/dto/question/MatchingQuestionDto.java, src/main/java/com/example/demo/dto/question/QuestionDto.java, src/main/java/com/example/demo/dto/question/QuestionMapper.java, src/main/java/com/example/demo/models/businesslogic/Matching.java, src/main/java/com/example/demo/models/businesslogic/domains/ProgrammingLanguageExpressionDomain.java, src/main/java/com/example/demo/models/entities/QuestionEntity.java, src/main/java/com/example/demo/models/entities/QuestionOptions/MatchingQuestionOptionsEntity.java, src/main/java/com/example/demo/models/entities/QuestionOptions/OrderQuestionOptionsEntity.java, src/main/java/com/example/demo/models/entities/QuestionOptions/QuestionOptionsEntity.java, src/main/js/client/components/feedback.tsx, src/main/js/client/components/next-question-btn.tsx, src/main/js/client/components/question/question-types/matching-question.tsx, src/main/js/client/components/question/question-types/order-question.tsx, src/main/js/client/store.tsx, src/main/js/client/types/interaction.ts, src/main/js/client/types/question-options.ts, src/main/js/client/types/question.ts, src/main/js/client/types/session-info.ts, src/main/js/client/types/user-info.ts, src/main/resources/application.properties, src/main/resources/com/example/demo/models/businesslogic/domains/programming-language-expression-domain-laws.json, src/test/java/com/example/demo/models/businesslogic/ProgrammingLanguageExpressionDomainTest.java, src/test/java/com/example/demo/models/businesslogic/SystemIntegrationTest.java, src/test/resources/data.sql
Сделал пример вопроса matching с типами + простые правила с ответами
Отображение для него не сделал.
=> [ProgrammingLanguageExpressionDomain] Generate and solve simple question

src/main/java/com/example/demo/Service/QuestionService.java, src/main/java/com/example/demo/models/businesslogic/Question.java, src/main/java/com/example/demo/models/businesslogic/domains/Domain.java, src/main/java/com/example/demo/models/businesslogic/domains/ProgrammingLanguageExpressionDomain.java, src/main/java/com/example/demo/models/businesslogic/domains/TestDomain.java, src/main/java/com/example/demo/models/entities/EnumData/QuestionType.java, src/main/java/com/example/demo/models/repository/QuestionRepository.java, src/main/resources/com/example/demo/models/businesslogic/domains/programming-language-expression-domain-questions.json, src/test/java/com/example/demo/models/businesslogic/ProgrammingLanguageExpressionDomainTest.java, src/test/java/com/example/demo/models/businesslogic/SystemIntegrationTest.java, src/test/resources/data.sql
All select logic separated from question store, can be changed to more efficient realization in future
=> Add simple local Questions database

src/main/java/com/example/demo/models/businesslogic/domains/Domain.java, src/test/java/com/example/demo/models/businesslogic/ProgrammingLanguageExpressionDomainTest.java, src/test/resources/data.sql
=> Сделал 2 exercise attempt без SystemIntegrationTest концепта

src/main/java/org/vstu/compprehension/controllers/BasicExerciseController.java
=> fix incorrect determining of correct interactions

src/main/java/org/vstu/compprehension/models/businesslogic/Question.java
Брать список ответов на вопрос только из последней интеракции
=> Use only last interaction

src/main/java/org/vstu/compprehension/Service/ExerciseService.java, src/main/java/org/vstu/compprehension/Service/QuestionService.java, src/main/java/org/vstu/compprehension/controllers/BasicExerciseController.java, src/main/java/org/vstu/compprehension/models/businesslogic/Tag.java, src/main/java/org/vstu/compprehension/models/businesslogic/domains/ProgrammingLanguageExpressionDomain.java, src/main/java/org/vstu/compprehension/models/entities/ExerciseEntity.java, src/main/resources/org/vstu/compprehension/models/businesslogic/domains/programming-language-expression-domain-questions.json, src/test/java/org/vstu/compprehension/models/businesslogic/SystemIntegrationTest.java, src/test/resources/data.sql
=> Remove duplicates functions in Test

pom.xml, src/main/java/org/vstu/compprehension/Service/FrontendService.java, src/main/java/org/vstu/compprehension/Service/QuestionService.java, src/main/java/org/vstu/compprehension/models/businesslogic/backend/JenaBackend.java, src/main/java/org/vstu/compprehension/models/businesslogic/domains/ControlFlowStatementsDomain.java, src/main/java/org/vstu/compprehension/models/businesslogic/domains/Domain.java, src/main/java/org/vstu/compprehension/models/businesslogic/domains/ProgrammingLanguageExpressionDomain.java, src/main/java/org/vstu/compprehension/models/businesslogic/domains/TestDomain.java, src/main/resources/org/vstu/compprehension/models/businesslogic/domains/programming-language-expression-domain-questions.json, src/test/java/org/vstu/compprehension/models/businesslogic/SystemIntegrationTest.java
For now some branches will cycle infinitely, others not
Judge realized by separate function as need question and answer and don't need backend.
=> Realize one branch of supplement questions

src/main/java/org/vstu/compprehension/models/businesslogic/domains/ProgrammingLanguageExpressionDomain.java, src/main/java/org/vstu/compprehension/models/entities/ViolationEntity.java, src/main/resources/org/vstu/compprehension/models/businesslogic/domains/programming-language-expression-domain-questions.json, src/main/resources/org/vstu/compprehension/models/businesslogic/domains/programming-language-expression-domain-supplementary-strategy.json, src/test/java/org/vstu/compprehension/models/businesslogic/SystemIntegrationTest.java
Realize new scheme of supplement questions 
(templates of questions, separate subsequent supplement graph, detailed law, explanation)
=> Realize new scheme of supplement questions

src/main/java/org/vstu/compprehension/models/businesslogic/domains/ProgrammingLanguageExpressionDomain.java, src/main/java/org/vstu/compprehension/models/entities/ViolationEntity.java, src/main/resources/org/vstu/compprehension/models/businesslogic/domains/programming-language-expression-domain-questions.json, src/main/resources/org/vstu/compprehension/models/businesslogic/domains/programming-language-expression-domain-supplementary-strategy.json, src/test/java/org/vstu/compprehension/models/businesslogic/SystemIntegrationTest.java
To find bugs and test at least one branch of supplement questions.
=> Add test to exercise with id 6 

src/main/java/org/vstu/compprehension/models/businesslogic/domains/Domain.java, src/main/java/org/vstu/compprehension/models/businesslogic/domains/ProgrammingLanguageExpressionDomain.java, src/main/resources/org/vstu/compprehension/models/businesslogic/domains/programming-language-expression-domain-questions.json, src/main/resources/org/vstu/compprehension/models/businesslogic/domains/programming-language-expression-domain-supplementary-strategy.json, src/test/java/org/vstu/compprehension/models/businesslogic/SystemIntegrationTest.java
Add last question with 0 answers to finish.
Add field isAnswerCorrect to InterpretSentence
Add supplementary on all base errors
=> Fix issues with supplementary

src/main/java/org/vstu/compprehension/models/businesslogic/domains/ProgrammingLanguageExpressionDomain.java, src/main/resources/org/vstu/compprehension/models/businesslogic/domains/programming-language-expression-domain-questions.json, src/main/resources/org/vstu/compprehension/models/businesslogic/domains/programming-language-expression-domain-supplementary-strategy.json, src/test/java/org/vstu/compprehension/models/businesslogic/SystemIntegrationTest.java
Fix same variants in question.
Refine supplementary structure
=> Fix supplement

src/main/java/org/vstu/compprehension/models/businesslogic/domains/ProgrammingLanguageExpressionDomain.java, src/main/resources/org/vstu/compprehension/models/businesslogic/domains/programming-language-expression-domain-questions.json, src/main/resources/org/vstu/compprehension/models/businesslogic/domains/programming-language-expression-domain-supplementary-strategy.json, src/test/java/org/vstu/compprehension/models/businesslogic/ProgrammingLanguageExpressionDomainTest.java, src/test/java/org/vstu/compprehension/models/businesslogic/SystemIntegrationTest.java
bug with interaction
bug with useless question
bugs with supplements structure
refine final messages
=> Fix supplement questions

src/main/java/org/vstu/compprehension/models/businesslogic/domains/ProgrammingLanguageExpressionDomain.java, src/main/resources/org/vstu/compprehension/models/businesslogic/domains/programming-language-expression-domain-questions.json, src/main/resources/org/vstu/compprehension/models/businesslogic/domains/programming-language-expression-domain-supplementary-strategy.json, src/test/java/org/vstu/compprehension/models/businesslogic/ProgrammingLanguageExpressionDomainTest.java, src/test/java/org/vstu/compprehension/models/businesslogic/SystemIntegrationTest.java
Each answer now can have more than 1 check and 2 transitions based on it. Each transition explicitly shows check, next question, detailed low and correctness
=> Move to transitions from each supplementary answer

src/main/java/org/vstu/compprehension/models/businesslogic/domains/ProgrammingLanguageExpressionDomain.java, src/main/resources/org/vstu/compprehension/models/businesslogic/domains/programming-language-expression-domain-laws.json, src/main/resources/org/vstu/compprehension/models/businesslogic/domains/programming-language-expression-domain-questions.json, src/test/java/org/vstu/compprehension/models/businesslogic/SystemIntegrationTest.java, src/test/java/org/vstu/compprehension/models/businesslogic/backend/PelletBackendTest.java, src/test/resources/data.sql
5 types of relations:
- part of left operand
- part of inner operand
- part of right operand
- is operand of another operator
- unrelated
=> Add question type that categorized all operations by AST relations

src/main/java/org/vstu/compprehension/models/businesslogic/domains/ProgrammingLanguageExpressionDomain.java, src/main/resources/org/vstu/compprehension/models/businesslogic/domains/programming-language-expression-domain-laws.json, src/main/resources/org/vstu/compprehension/models/businesslogic/domains/programming-language-expression-domain-questions.json, src/test/java/org/vstu/compprehension/models/businesslogic/SystemIntegrationTest.java, src/test/resources/data.sql
3 type:
- less precedence
- higher precedennce
- same precedence
=> Add match question for relative precedence

src/main/resources/org/vstu/compprehension/models/businesslogic/domains/control-flow-statements-domain-questions.json
(mistake sets are still not complete)
=> CtrlFlow questions: add mistake names as "negativeLaws"

src/main/java/org/vstu/compprehension/models/businesslogic/Strategy.java, src/test/java/org/vstu/compprehension/models/businesslogic/SystemIntegrationTest.java
Новая стратегия генерации question request
=> New generation question request

src/main/java/org/vstu/compprehension/Service/FrontendService.java, src/main/java/org/vstu/compprehension/Service/QuestionService.java, src/main/java/org/vstu/compprehension/models/businesslogic/domains/ControlFlowStatementsDomain.java, src/main/java/org/vstu/compprehension/models/businesslogic/domains/Domain.java, src/main/java/org/vstu/compprehension/models/businesslogic/domains/ProgrammingLanguageExpressionDomain.java, src/main/java/org/vstu/compprehension/models/businesslogic/domains/TestDomain.java, src/main/resources/org/vstu/compprehension/models/businesslogic/domains/programming-language-expression-domain-messages.json
=> Localization evaluation domain

src/main/java/org/vstu/compprehension/models/businesslogic/Question.java, src/main/java/org/vstu/compprehension/models/businesslogic/domains/ControlFlowStatementsDomain.java, src/main/java/org/vstu/compprehension/models/businesslogic/frontend/QuestionFront.java
Fix questionName when copy a question.
=> Question has (proxy-)getter .getQuestionName() now

src/main/java/org/vstu/compprehension/models/businesslogic/Strategy.java, src/main/java/org/vstu/compprehension/models/businesslogic/domains/ProgrammingLanguageExpressionDomain.java, src/main/resources/org/vstu/compprehension/models/businesslogic/domains/programming-language-expression-domain-laws.json, src/test/java/org/vstu/compprehension/models/businesslogic/backend/PelletBackendTest.java, src/test/resources/has-operand-test-data.json
Use noValue and drop jena builtins (close world assumption) to remove steps from model.
Has to be careful with noValue
=> Speed up expressions domain by using jena optimizations

src/main/resources/templates/index.html
(cherry picked from commit 3258ec63d5c9f5fd2e3b3fa95855b60869c8b1c2)
=> add missing files to prev commit (#177)

src/main/java/org/vstu/compprehension/config/WebSecurityConfig.java
(cherry picked from commit 19ecc92d65e4cc3808890447ee43724b90b4eaae)
=> add test users (#189)

.jpb/jpb-settings.xml, pom.xml, src/main/java/org/vstu/compprehension/models/businesslogic/domains/Domain.java, src/main/java/org/vstu/compprehension/models/businesslogic/storage/RdfStorage.java, src/main/java/org/vstu/compprehension/models/businesslogic/storage/RemoteFileService.java, src/main/java/org/vstu/compprehension/models/entities/DomainEntity.java, src/main/java/org/vstu/compprehension/models/entities/DomainOptionsEntity.java, src/main/resources/db/changelog/2022-01-06/2022-01-06-01-changelog.xml, src/main/resources/db/changelog/db.changelog-master.xml, src/test/resources/data.sql
Создана миграция для таблицы домена и новая JSON-entity DomainOptionsEntity
=> RdfService, RemoteFileService и конфиг Домена в БД

src/main/java/org/vstu/compprehension/config/WebSecurityConfig.java
(cherry picked from commit 3e235ace63c92332d3f2aa21dee49be308987f6f)
=> add rfbr user (#191)

src/main/java/org/vstu/compprehension/models/businesslogic/Question.java, src/main/java/org/vstu/compprehension/models/businesslogic/backend/JenaBackend.java, src/main/java/org/vstu/compprehension/models/businesslogic/domains/ControlFlowStatementsDomain.java, src/main/java/org/vstu/compprehension/models/businesslogic/domains/Domain.java, src/main/java/org/vstu/compprehension/models/businesslogic/domains/ProgrammingLanguageExpressionDomain.java, src/main/java/org/vstu/compprehension/models/businesslogic/domains/TestDomain.java, src/main/java/org/vstu/compprehension/models/businesslogic/storage/AbstractRdfStorage.java, src/main/java/org/vstu/compprehension/models/businesslogic/storage/GraphRole.java, src/main/java/org/vstu/compprehension/models/businesslogic/storage/LocalRdfStorage.java, src/main/java/org/vstu/compprehension/models/businesslogic/storage/RdfStorage.java, src/main/resources/org/vstu/compprehension/models/businesslogic/domains/control-flow-statements-domain-laws.json
локальные файлы скачиваются отдельно. их нужно поместить в c:\Temp2\compp\.
=> Банк вопросов CtrlFlow работает локально

src/main/java/org/vstu/compprehension/models/businesslogic/domains/ProgrammingLanguageExpressionDomain.java
- correcly count integral_complexity in question generation
- fix bug with supplementary question and new end_token
=> Minor bug fixes

.gitignore, modules/core/src/main/java/org/vstu/compprehension/models/businesslogic/backend/DecisionTreeReasonerBackend.java, modules/core/src/main/java/org/vstu/compprehension/models/businesslogic/domains/helpers/ProgrammingLanguageExpressionRDFTransformer.java, modules/core/src/main/java/org/vstu/compprehension/models/businesslogic/storage/SerializableQuestion.java, modules/core/src/main/java/org/vstu/compprehension/models/entities/SupplementaryStepEntity.java, modules/core/src/main/resources/org/vstu/compprehension/models/businesslogic/domains/programming-language-expression-domain-model/domain.loqi
Добавлена работа по исправлению наводящих вопросов, работающих по дереву решений домена выражений. Основная проблема была в неподдерживаемых концептах (они не были заложены в раннюю версию домена).
=> Fix expr supplementry questions

modules/background-server/src/main/java/org/vstu/compprehension/config/JobsConfig.java, modules/background-server/src/main/java/org/vstu/compprehension/jobs/tasksgeneration/TaskGenerationJob.java, modules/background-server/src/main/resources/application.yml
- remove exit(0)
- set default run-once property to false
- disable controlflow generation job
=> task generation job: remove exit(0), fix default job properties
